
//=============================================================================
//                       Hypercom Inc
//                      (c) Copyright 2002
//=============================================================================
#ifndef _PCLTEXT_H_
#define _PCLTEXT_H_
//=============================================================================
//
// Module overview:             pcltext.h
//      PCL defintions, data, and functions
//
//=============================================================================

//=============================================================================
// Public defines and typedefs
//=============================================================================
//! Message Text Identifiers
//! Messages are defined in pclengtext.c and pclestext.c
enum pcltextDef_id
{
	LangId,
	Merchant,
	Srv,
	Csh,
	Till,
	Void_s,
	Food,
	Cash,
	Benefit,
	Void,
	Expire,
	Batch,
	Invoice,
	Date,
	Time,
	Rrn,
	AuthN,
	Fcs,
	Avs,
	AvailB,
	PclToday,
	Base,
	Tax,
	Bar,
	Surcharge,
	Tip,
	Total,
	TipGuide,
	SaleAmt,
	CashBack,
	Fee,
	AmountDue,
	NoRefundsAllow,
	OfflineEntered,
	FoodBal,
	CashBal,
	Duplicate,
	SignatureNotReq,
	AvsCanceled,
	PclTrainingMode,
	IAuthorizeElect,
	FundFromMyAccount,
	OrPaperDraft,
	ForTheAmount,
	InTheEvent,
	Unpaid,
	Point,
	Return,
	ItemFee,
	TransferFunds,
	ForTAmount,
	IAgree,
	According,
	MerchantAgreement,
	TransactFailed,
	NormalFont,
	S_ABCDEFGHIJ,
	S_KLMNOPQRST,
	S_UVWXYZ,
	S_abcdefghi,
	S_klmnopqrst,
	S_uvwxyz0123,
	S_SetSymbol1,
	S_SetSimbols2,
	Normal,
	Double,
	FontChange,
	TheEnd,
	AuditReport,
	AllAcquirers,
	InvTrans,
	Server,
	Cashr,
	Auth,
	CardNumber,
	CardType,
	Cashbk,
	TipTotal,
	CashTotal,
	TransTotal,
	Shift,
	Star,
	OpenTabs,
	PclInvTrans,
	TransTotals,
	ByIssuer,
	Cashier,
	PclServer,
	PclTill,
	GranTotals,
	NothingToPrint,
	Unadj,
	Audit,
	Terminal,
	DatabaseReport,
	TermEpromConfig,
	TermConfig,
	AcqId,
	IssuerID,
	CardRangeId,
	Id_Descriptor,
	Visa2Id,
	AddPromptId,
	RawData,
	ReceivedData,
	SendData,
	HostTotals,
	Debit,
	AcqTable,
	MerchantN,
	TerminalID,
	Sales,
	Refunds,
	CashBk,
	Amount,
	Log,
	On,
	Report,
	SettlStatus,
	NotOfRec,
	NumOfRec,
	RecUpload,
	PleasSettl,
	UploadFail,
	HelpDesk,
	lblPerfRpt,
	lblTotAprorv,
	lblTotDenials,
	lblTotManual,
	lblTotSwipe, 
	TransCount,
	lblTransCount,
	lblTotRedials,
	lblTottimeout,
	lblTotRetrans,
	Period,
	To,
	Comm,
	lblConfigRpt,
	Adjust,
	Off, 		

	LAST_PCLTEXTDEF_ID		// This MUST be the last definition
};

enum pcltextExt_id
{
	Percent1,
	Percent2,
	Percent3,
	lblAcqAvail,		  
	lblConfbyAcq,
	NII,
	CardAcceptTerm,
	CardAcceptMerc,
	VisaITermId,
	NotASettlement,
	IgnoreHostTime,
	ISDNprotocol,
	ErcCompression,
	CurrentBatch,
	NextBatch,
	MaxSettleAttemp,
    lblSignOnHostInform,
	lblTransHostInform,
	Primary,
	PhoneNum,
	ConnectTime,
	DialAttemps,
	ModemMode,
	Secondary,
    lblSettleHostInf,
	lblIssuerTab,          //Issuer Table
	lblIssAvail,
	lblConfigByIss,
	CaptureTrans,
	PrintReceipt,
	CaptureReceipt,
	FloorLimit,
	ReauthPercent,
	AchCheckTrans,
	Use6Digit,
	PinEntryReq,
	AllowCashBack,
	AllowCashOnly,
	lblProcOption,
	InvoiceN,
	ManualPan,
	Mod10Check,
	IgnoreTrack,
	ExpiryDate,
	CheckExpiry,
	OfflineAllow,
	AdjustAllow,
	VoiceReferral,
	PromptForTax,
	lblAvsOptions,
	AvsEnab,
	PromptAddress,
	PromptZipCode,
	lblBlockTrans,
	CardVerif,
	BalInq,
	lblPinRequired,
	lblCardRangTab,
	lblCardRangAvai,
	lblConfByCard,
	CardRang,
	PanRangeLow,
	PanRangeHigh,
	PanLength,
	lblID,
	lblName,
	lblCrnum,
	SupportIn,
	IUndestand,
	MayBeConverted,
	DebitMy,
	ItemIs,
	IWillPay,
	MaximumAmount,
	LawWith,
	FromMy,
	FundsTransfer,
	MannerSer,

	
	LAST_PCLTEXTEXT_ID		// This MUST be the last definition
};


//=============================================================================
// Public data declarations
//=============================================================================


//=============================================================================
// Public function declarations
//=============================================================================


#endif // _PCLTEXT_H_
