/********************************************************************
 *                            Hypercom Inc                          *
 *                        (c) Copyright 2006                        *
 ********************************************************************/

#ifndef OSPLATFORM_INC
#define OSPLATFORM_INC

#if !defined(MAKE_OPTIMUM) && !defined(MAKE_VIKING)
#error Either MAKE_VIKING or MAKE_OPTIMUM has to be defined!
#endif

#endif //; OSPLATFORM_INC
