/********************************************************************
 *                            Hypercom Inc                          *
 *                        (c) Copyright 2006                        *
 ********************************************************************/

#ifndef GUIFONTS_INC
#define GUIFONTS_INC

#include <osgui.h>

//----------------------------------------------------------------------------
// Special symbol equates for the extended fonts
//----------------------------------------------------------------------------
#define CHR_BKSLASH     0x80        // Backslash
#define CHR_UPARROW     0x81        // Up arrow
#define CHR_DOWNARROW   0x82        // Down arrow
#define CHR_RETARROW    0x83        // Return arrow
#define CHR_CIRCARROW   0x84        // Circular arrow
#define CHR_BULLET      0x85        // Bullet/dot
#define CHR_LINEUP      0x86        // Triangle pointing up
#define CHR_LINEDOWN    0x87        // Triangle pointing down
#define CHR_PAGEUP      0x88        // Two triangles pointing up
#define CHR_PAGEDOWN    0x89        // Two triangles pointing down
#define CHR_BRITPOUND   0x9C        // British Pound
#define CHR_JPNYEN      0x9D        // Japanese Yen
#define CHR_EURODOLL    0xAF        // Euro Dollar

#endif
