/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.9 2005/01/07 09:37:18 dts12 Exp $
 */
#ifndef FIMPEOID_H
#define FIMPEOID_H

/*
 * function declarations 
 */
void            init_fimpeOID(void);
Netsnmp_Node_Handler handle_sysMrchntinfoBlk;
Netsnmp_Node_Handler handle_sysMdlNum;
Netsnmp_Node_Handler handle_sysPartNum;
Netsnmp_Node_Handler handle_sysHwVer;
Netsnmp_Node_Handler handle_sysSrlNum;
Netsnmp_Node_Handler handle_sysPtidNum;
Netsnmp_Node_Handler handle_sysMdmModId;
Netsnmp_Node_Handler handle_sysPinPadInfo;
Netsnmp_Node_Handler handle_sysPRNInfo;
Netsnmp_Node_Handler handle_sysOsVer;
Netsnmp_Node_Handler handle_sysMfgLotNum;
Netsnmp_Node_Handler handle_sysRamSz;
Netsnmp_Node_Handler handle_sysFlashSz;
Netsnmp_Node_Handler handle_sysTime;
Netsnmp_Node_Handler handle_sysDate;
Netsnmp_Node_Handler handle_sysFreeRam;
Netsnmp_Node_Handler handle_sysFreeFlash;
Netsnmp_Node_Handler handle_sysBatStat;
Netsnmp_Node_Handler handle_fimpeTotalTransactions;
Netsnmp_Node_Handler handle_fimpeOnLineSales;
Netsnmp_Node_Handler handle_fimpeOffLineSales;
Netsnmp_Node_Handler handle_fimpeRefundTransactions;
Netsnmp_Node_Handler handle_fimpePreauthTransactions;
Netsnmp_Node_Handler handle_fimpeAdjustSaleTransactions;
Netsnmp_Node_Handler handle_fimpeManualEntries;

#endif                          /* FIMPEOID_H */
